version: "3.7"
services:
  postgres-simulation:
    image: postgres:alpine3.15
    container_name: postgres-simulation
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: $PGDATA
    networks:
      - shared-network
    volumes:
      - postgres-simulation-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  mosquitto-simulation:
    image: eclipse-mosquitto:2.0.14
    container_name: mosquitto-simulation
    networks:
      - shared-network
    volumes:
      - mosquitto-simulation-data:/mosquitto/data
      - mosquitto-simulation-log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1884:1883
      - 9002:9001

  simulation-api:
    build: ./Fire-API-simulation
    image: simulation-api
    container_name: simulation-api
    networks:
      - shared-network
    ports:
     - 8000:8000
    depends_on:
      - postgres-simulation

  java-simulator-simulation:
    build: ../simulateurJava/Simulator
    image: java-simulator-simulation
    container_name: java-simulator-simulation
    networks:
      - shared-network
    depends_on:
      - simulation-api
      - mosquitto-simulation

volumes:
  postgres-simulation-data:
    external: true
  mosquitto-simulation-data:
    external: true
  mosquitto-simulation-log:
    external: true

networks:
  shared-network:
    external: true