version: "3.7"
services:
  postgres-emergency:
    image: postgres:alpine3.15
    container_name: postgres-emergency
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: $PGDATA
    networks:
      - shared-network
    volumes:
      - postgres-emergency-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432

  pgadmin4:
    image: dpage/pgadmin4:6
    container_name: pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    networks:
      - shared-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 16543:80
    depends_on:
      - postgres-emergency

  mosquitto-emergency:
    image: eclipse-mosquitto:2.0.14
    container_name: mosquitto-emergency
    networks:
      - shared-network
    volumes:
      - mosquitto-emergency-data:/mosquitto/data
      - mosquitto-emergency-log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001
  
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    hostname: influxdb
    environment:
      INFLUX_DB: $INFLUX_DB
      INFLUXDB_USER: $INFLUXDB_USER
      INFLUXDB_USER_PASSWORD: $INFLUXDB_USER_PASSWORD
    networks:
      - shared-network
    volumes:
      - influxdb-data:/var/lib/influxdb
      - influxdb-data:/var/lib/influxdb2
      - influxdb-data:/etc/influxdb2
    ports:
      - 8086:8086

  telegraf:
    image: telegraf:1.21.1
    container_name: telegraf
    links:
      - influxdb:influxdb
    networks:
      - shared-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - mosquitto-emergency
      - influxdb

  grafana:
    image: grafana/grafana:8.3.3-ubuntu
    container_name: grafana
    links:
      - influxdb:influxdb
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,\
                          grafana-influxdb-08-datasource,\
                          grafana-kairosdb-datasource,\
                          grafana-piechart-panel,\
                          grafana-simple-json-datasource,\
                          grafana-worldmap-panel"
    networks:
      - shared-network
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb

  emergency-api:
    build: ./API-Emergency
    image: emergency-api
    container_name: emergency-api
    networks:
      - shared-network
    ports:
     - 8001:8000
    depends_on:
      - postgres-emergency

  java-emergency-manager:
    build: ../simulateurJava/Emergency/Emergency
    image: java-emergency-manager
    container_name: java-emergency-manager
    networks:
      - shared-network
    depends_on:
      - simulation-api
      - emergency-api
      - mosquitto-emergency

volumes:
  postgres-emergency-data:
    external: true
  pgadmin-data:
    external: true
  influxdb-data:
    external: true
  grafana-data:
    external: true
  mosquitto-emergency-data:
    external: true
  mosquitto-emergency-log:
    external: true

networks:
  shared-network:
    external: true